name: Build the container image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - published

env:
  image_name: ghcr.io/williamjacksn/pblive

jobs:
  build:
    name: Build the container image
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Build the container image
        uses: docker/build-push-action@v2.10.0
        with:
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: |
            ${{ env.image_name }}
          load: true
          tags: ${{ env.image_name }}

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          password: ${{ github.token }}
          username: ${{ github.actor }}

      - name: Push latest image to registry
        if: github.event_name == 'push'
        run: docker image push ${{ env.image_name }}

      - name: Tag and push release image to registry
        if: github.event_name == 'release'
        run: |
          docker image tag ${{ env.image_name }}:latest ${{ env.image_name }}:${{ github.event.release.tag_name }}
          docker image push ${{ env.image_name }}:${{ github.event.release.tag_name }}
